<?php
//$listitems = $this->getListslider();
//if(!$listitems){
//    return false;
//}
//$endItem = end($listitems);
////?>
<!---->
<!--<div class="sl-parallax scene carousel slide" id="scene" data-ride="carousel">-->
<!--    <ol class="carousel-indicators">-->
<!--        --><?php //foreach ($listitems as $index => $item) {
//            $active = $index == 0 ? 'active' : '';
//            ?>
<!--            <li data-target="#scene" data-slide-to="--><?php //echo $index ?><!--" class="--><?php //echo $active ?><!--"></li>-->
<!--        --><?php //} ?>
<!--    </ol>-->
<!--    <div class="carousel-inner" role="listbox">-->
<!--        --><?php //foreach ($listitems as $index => $item) {
//        $active = $index == 0 ? 'active' : '';
//        ?>
<!--            <div class="item --><?php //echo $active; ?><!-- sl-content">-->
<!--                <div class="hl-wrp row">-->
<!--                    <div class="sl-bg">-->
<!--                        <img src="--><?php //echo Mage::getBaseUrl('media').'/ts_headerslider/'.$item['image']; ?><!--" class="layer">-->
<!--                    </div>-->
<!--                    <div class="hl-img-shadow">-->
<!--                        <div class="hl-shadow layer" data-depth="0.6"></div>-->
<!--                    </div>-->
<!--                    <div class="hl-img col-lg-4 col-md-5 col-sm-6 col-xs-8">-->
<!--                        --><?php //if($item['feature_image']) { ?>
<!--                            <img src="--><?php //echo Mage::getBaseUrl('media').'/ts_headerslider/'.$item['feature_image']; ?><!--" class="layer" data-depth="0.4">-->
<!--                        --><?php //} ?>
<!--                    </div>-->
<!--                    <div class="hl-box-wrp col-lg-5 col-sm-7 col-sm-offset-4 col-xs-10 col-xs-offset-1">-->
<!--                        <div class="layer hl-box" data-depth="0.2">-->
<!--                            <h1 class="text-center uppercase">-->
<!--                                <span class="nd-color">--><?php //echo $item['feature_description']; ?><!--</span><br>-->
<!--                                <span class="text-white">--><?php //echo $item['title']; ?><!--</span>-->
<!--                            </h1>-->
<!--                            <p class="text-md text-center text-white">-->
<!--                                --><?php //echo $item['description']; ?>
<!--                            </p>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        --><?php //} ?>
<!--        <a class="left carousel-control" href="#scene" role="button" data-slide="prev">-->
<!--            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>-->
<!--            <span class="sr-only">--><?php //echo  Mage::helper('headerslider')->__('Previous'); ?><!--</span>-->
<!--        </a>-->
<!--        <a class="right carousel-control" href="#scene" role="button" data-slide="next">-->
<!--            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>-->
<!--            <span class="sr-only">--><?php //echo  Mage::helper('headerslider')->__('Next'); ?><!--</span>-->
<!--        </a>-->
<!--    </div>-->
<!--</div>-->

<?php
$lang = (Mage::app()->getStore()->getStoreID() == 1) ? 'en' : 'vn';
?>
<div class="col-md-12 col-sm-12">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_main_menu_'.$lang)->toHtml(); ?>
</div>
